# On new commit to master, trigger another pipeline run
trigger:
  - master

pool:
  vmImage: 'windows-latest'

# Make Release builds
variables:
  buildConfiguration: 'Release'

steps:


  # Build the project
  - task: DotNetCoreCLI@2
    displayName: '.NET Build'
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
      projects: 'Consumer/Consumer.csproj'

  # - task: CmdLine@2
  #   displayName: 'Check directory contents'
  #   inputs:
  #     script: ls


  # Build the project
  - task: DotNetCoreCLI@2
    displayName: '.NET Restore Tests'
    inputs:
      command: 'restore'
      arguments: '--configuration $(buildConfiguration)'
      projects: 'Calculator.Tests/Calculator.Tests.csproj'
  # Build the project
  - task: DotNetCoreCLI@2
    displayName: '.NET Build Tests'
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
      projects: 'Calculator.Tests/Calculator.Tests.csproj'
    # Run unit tests
  - task: DotNetCoreCLI@2
    displayName: '.NET Unit Tests'
    inputs:
      command: 'test'
      arguments: '--configuration $(buildConfiguration)'
      projects: 'Calculator.Tests/Calculator.Tests.csproj'

    # Bundle the project into a NuGet package
  - task: DotNetCoreCLI@2
    displayName: '.NET pack project'
    inputs:
      command: 'pack'
      arguments: '--configuration $(buildConfiguration)'
      packagesToPack: 'Consumer/Consumer.csproj'
      nobuild: true
      versioningScheme: 'off'

  - task: NuGetCommand@2
    displayName: 'Push NuGet Package'
    inputs:
      command: 'push'
      feedsToUse: 'select'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      vstsFeed: calculator/CalculatorFeed
      publishVstsFeed: calculator/CalculatorFeed
      versioningScheme: 'off'
      allowPackageConflicts: true
